config_version: "1"

iothub:
  iothub_hostname: lefitche-hub-3.azure-devices.net
  iothub_name: lefitche-hub-3
  authentication_method: connection_string

## Optional. If not provided a self-signed CA will be generated
# certificates:
#   root_ca_cert_path: ""
#   root_ca_cert_key_path: ""
configuration:
  template_config_path: "./templates/device_config.toml"
  default_edge_agent: "$upstream:8000/azureiotedge-agent:1.2.0-rc4"
edgedevices:
  device_id: edge-root
  # hostname: "FQDN or IP" ## This is optional. If provided, install.sh will not prompt user for this value
  # deployment: "./templates/device_config.toml" ## This is optional. If provided, the given deployment file will be applied to the newly created device identity
  edge_agent: "mcr.microsoft.com/azureiotedge-agent:1.2.0-rc4" # If not provided, default_edge_agent will be used
  child:
    - device_id: edge-A
      # hostname: "FQDN or IP"
      # deployment: "./templates/device_config.toml"
      child:
        - device_id: edge-AA
        - device_id: edge-AB
          child:
            - device_id: edge-ABA
    - device_id: edge-B
    - device_id: edge-C
      child:
        - device_id: edge-CA
          child:
            - device_id: edge-CAA
              child:
                - device_id: edge-CAAA
