iothub:
  iothub_hostname: lefitche-hub-3.azure-devices.net
  iothub_name: lefitche-hub-3
  authentication_method: connection_string
# certificates:
#   root_ca_cert_path: ""
#   root_ca_cert_key_path: ""
configuration:
  template_config_path: "./templates/device_config.toml"
edgedevices:
  device_id: edge-root
  child:
    - device_id: edge-A
      child:
        - device_id: edge-AA
        - device_id: edge-AB
          child:
            - device_id: edge-ABA
    - device_id: edge-B
    - device_id: edge-C
      child:
        - device_id: edge-CA
          child:
            - device_id: edge-CAA
              child:
                - device_id: edge-CAAA
