iothub:
  iot_hub_resource_group: test
  iot_hub_name: lefitche-hub-3
  authentication_method: connection_string
certificates:
  root_ca_cert_path: ""
  root_ca_cert_key_path: ""
configuration:
  template_config_path: "./templates/device_config.toml"
  default_deployment: ""
edgedevices:
  device_id: edge-root
  child:
    - device_id: edge-1
      child:
        - device_id: edge-1.1
        - device_id: edge-1.2
    - device_id: edge-2
    - device_id: edge-3
      child:
        - device_id: edge-3.1
          child:
            - device_id: edge-3.1.1
              child:
                - device_id: edge-3.1.1.1
