# Leave this section out
# Its values will automatically be filled in
#
# hostname = "192.168.0.180"
# parent_hostname = "192.168.0.129"
#
# [provisioning]
# source = "manual"
# iothub_hostname = ""
# device_id = ""
#
# [provisioning.authentication]
# method = "sas"
# device_id_pk = { value = "" }
#
# trust_bundle_cert = ""
#
# [edge_ca]
# cert = "<File URI path to the device full chain CA certificate unique to this device.>"
# pk = "<File URI path to the device CA private key unique to this device.>"
#
# [agent.config]
# image = "mcr.microsoft.com/azureiotedge-agent:1.0"

[agent]
name = "edgeAgent"
type = "docker"

[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"

[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"

[moby_runtime]
uri = "unix:///var/run/docker.sock"
network = "azure-iot-edge"
