// Autogenerated by https://transform.tools/json-to-rust-serde

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateResponse {
    pub authentication: Authentication,
    pub capabilities: Capabilities,
    pub cloud_to_device_message_count: i64,
    pub connection_state: String,
    pub connection_state_updated_time: String,
    pub device_id: String,
    pub device_scope: String,
    pub etag: String,
    pub generation_id: String,
    pub last_activity_time: String,
    pub status: String,
    pub status_reason: ::serde_json::Value,
    pub status_updated_time: String,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Authentication {
    pub symmetric_key: SymmetricKey,
    #[serde(rename = "type")]
    pub type_field: String,
    pub x509_thumbprint: X509Thumbprint,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SymmetricKey {
    pub primary_key: Option<String>,
    pub secondary_key: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct X509Thumbprint {
    pub primary_thumbprint: Option<String>,
    pub secondary_thumbprint: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Capabilities {
    pub iot_edge: bool,
}
